channels:
- conda-forge
dependencies:
- python=3.12.10
- pip<=25.0.1
- pip:
  - mlflow==2.22.0
  - numpy==1.26.2
  - pandas==2.1.4
  - scikit-learn==1.3.2
  - scipy==1.11.4
  - xgboost==3.0.2
name: mlflow-env
