name: Deploy to Databricks

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = $DATABRICKS_HOST" >> ~/.databrickscfg
          echo "token = $DATABRICKS_TOKEN" >> ~/.databrickscfg

      - name: Deploy code to Databricks
        run: |
          databricks workspace import_dir ./src /Repos/ricciots@uwindsor.ca/intel-sweep --overwrite

      - name: Copy configuration files to DBFS
        run: |
          databricks fs cp src/data/equities.csv dbfs:/FileStore/equitus.csv --overwrite
          databricks fs cp src/data/stocks.csv dbfs:/FileStore/stocks.csv --overwrite